[package]
name = "tuple_filter_example"
version = "0.1.0"
edition = "2021"

[dependencies]
arrow = { version = "52", features = ["pyarrow"] }
pyo3 = { version = "0.21", features = ["extension-module", "abi3", "abi3-py38"] }
